### PR TITLE
used template

### PR DESCRIPTION
**Pull request by CodeDoes**

### CODE REVIEW

**Comment by krux02** [comment]
That is actually very good compression on the source code. I think I just didn't like the backtick operator for this use case, that is why I din't use it. But overall I like it.

**Comment by CodeDoes** [comment]
Any recommendations? How could it be done better? maybe a macro then a template?

**Comment by krux02** [comment]
Well the super verbose version was the version was the best that I could come up with. So I think this really is an improvement. But I have a project going on where I compile functions that are written in Nim with this glm library to glsl. If this change doesn't break my project, I will accept the PR. I like it.

**Comment by krux02** [comment]
merged manually.

**Pull request closed without merging**
