### PR TITLE
added diag=

### PR DESCRIPTION
**Pull request by CodeDoes**

### CODE REVIEW

**Comment by krux02** [comment]
This is really useful, thank you. I didn't think about it, but it makes sense. Did you try to make it work for non square matrices, too? It would be nice if you could make it work like the normal diag works on non-square matrices.

**Comment by CodeDoes** [comment]
```
| x o o |
| o x o |
| o o x |
| x o o |
| o x o |
```
Like this?

**Comment by CodeDoes** [comment]
I'm just following the diag proc already implemented. I wanted some way of setting the `scale` of the matrix

**Comment by krux02** [comment]
```
| a o o |
| o b o |
| o o c |
| x o o |
```

Like this. and then you can set the ``a b c`` part of the matrix through ``diag=``.  Your ``diag=`` proc currently only matches on square matrices.

**Comment by krux02** [comment]
As said in the other comment, you do not set the scale of a matrix like this. You will most likely just break the matrix. You can use [scale](https://github.com/stavenko/nim-glm/blob/master/glm/mat_transform.nim#L82) or [scaleInpl](https://github.com/stavenko/nim-glm/blob/master/glm/mat_transform.nim#L77) for this.

**Comment by krux02** [comment]
merged it manually with tests.

**Pull request closed without merging**
