### PR TITLE
changed formatting

### PR DESCRIPTION
**Pull request by CodeDoes**
I can't really see the `$` representation in my console (on vscode) I would prefer the default be different

### CODE REVIEW

**Comment by krux02** [comment]
Well I can accept that the characters that I have chosen to represent the matrix are not widely supported in every font and terminal, I think your change actually introduced an entirely new problem. When you print the matrix like this ``[[a,b],[c,d]]`` I would assume that the components like `[a,b]` are column vectors of the matrix, and therefore the representation would be a transposed representation of what is actually printed.  So replacing the brace characters with only ``|`` for everything would work better.

**Comment by CodeDoes** [comment]
what format would be better. I see for quat quatf was used, would something similar suffice? or should I use ```nim
Mat[4,4,float](
  Vec[4.float](0.0,0.0,0.0,0.0),
  Vec[4.float](0.0,0.0,0.0,0.0),
  Vec[4.float](0.0,0.0,0.0,0.0),
  Vec[4.float](0.0,0.0,0.0,0.0))
```

**Comment by krux02** [comment]
well a row in the output is not a vector component of the matrix. A vector component of the matrix is actually a column of the matrix and my output procedure creates a column. Your ``$`` implementation should not give the impression as if it would be row based. Therefore I don't like any ``$`` implementation that has puts an individal row into braces like ``[x,y,z,w]``. As I said  a matrix output like the matrix below would be ok:

```
| 1  2 |
| 3  4 |
```
It's not perfect, but I could live with it.

**Comment by CodeDoes** [comment]
Yes. the current implementation ffe97adaf9bd2d37e4cb8097c6ccc473657c22d5 makes a `$` repr that looks as follows
```
|| 1  2  3  4 |
 | 5  6  7  8 |
 | 9  0  1  2 ||
```
The || at the beginning and the end make it easy to distinguish where one starts and another ends. At the end of the day I want you're opinion on which would be best. Failing that. How to get unicode to display in vscode's console.

**Comment by krux02** [comment]
I don't like the `||` and the beginning and the end at all. They hint a line based layout, and that is clearly not what it is. The output is a 2D layout and it should visually be interpreted as a 2D layout. So if you add something in the corners it should be at all 4 corners, not just top left and bottom right.

What do you think about this?

```
 / 1  2  3  4 \
 | 5  6  7  8 |
 \ 9  0  1  2 /
```

The top one is the current version. When you have a compatible font it look great. The second one I just wanted to point out as another lice looking alternative. That is what I want to immitate with the slashes in the corners.

```
⎡1  2  3  4⎤
⎢5  6  7  8⎥
⎣9  0  1  2⎦

⎛1  2  3  4⎞
⎜5  6  7  8⎟
⎝9  0  1  2⎠
```

**Comment by krux02** [comment]
I came up with a different solution. It is also mentioned in the readme.

**Comment by CodeDoes** [comment]
conceptually clear and console output friendly

**Comment by krux02** [comment]
You are saying "console output friendly". I use the unicode characters on the console, and I have no problem at all. But I am on linux, might it be that it is a windows problem? I can default to ASCII characters for windows builds.

**Comment by krux02** [comment]
I made a change. The `$` operator is now always pure ASCII on windows.

**Comment by CodeDoes** [comment]
The characters your using are ascii already. They give me strange characters like `ΓÄÑ` or just a block. I don't know if its just me

**Comment by krux02** [comment]
No the characters that I am using are not ascii at all. They are utf8 encoded. You see incorrect characters, that is a sign that the terminal doesn't use utf8. When you see a square instead of a character, it normally means that the font that you are using does not support that character.

**Pull request closed without merging**
