### PR TITLE
take over my codebase

### PR DESCRIPTION
**Pull request by krux02**
I am using this library for quite some time now, because it was the first vector library that I found, and it had a familiar name, glm. But there were quite some smaller issues in this library, that I did not see myself able to fix, because of the nature how this library was written (macros that generate code). I basically rewrote almost everything. Here are the things I changed:

 *   the type is now an object containing an array (not a distinct array anymore)
 *   everything except swizzling is based on generics
 *   more operator support `v1.yz += vec2f(7)` just works
 *   nicer string method with column alignment
 *   quaternion support
 *   smaller things

### CODE REVIEW

**Comment by johnnovak** [comment]
Hi @krux02 my story is similar to yours. I started using nim-glm it because it got `glm` in the name then ran into issues that were hard to fix due to the macro usage. My specific problem was optimisation related, see here https://github.com/stavenko/nim-glm/pull/18

I think what you're doing here is a good approach as it's much easier to optimise an explicit codebase like this. I also saw you made almost everything inline, that's good 👍 In the end, I started writing my own simple vector/matrix lib that I can optimize to my linking, but if this goes in, I'll have another look at the performance and I might start using `nim-glm` again.

Overall, nice effort, cheers! :)

**Comment by krux02** [comment]
@johnnovak I did not yet do any performance analysis, or real optimizations for it. My inline calls are just based on your issue, and my feeling, where it might be a good idea to use inline. But I did take performance into concideration for all the algorithms, but the focus was more on simple code. I think the most and easiest performance could generated, if the dot product, and element wise operations (`+-*/`) get some simd code, but I have no knowledge about how I could implement that. All other algorithms are implemented to use scalar products and vector operations, instead of loops. So they have potential to be faster.

One think I should mention though, I just realized, that I should have tested more, before actually creating this pull request, I am currently resolving some problems this version had, because I did not run it in my own codebase.

**Comment by krux02** [comment]
All my code now also works on this version of glm.

**Comment by johnnovak** [comment]
Cool, adding more tests is also a good thing. I might be able to help you with the SIMD stuff later, although I'm still just learning how to do that with Nim.

**Comment by stavenko** [comment]
Well, this pull request changes everything. Since I do not use `nim` today, I cannot say, that it's good working pattern, when you guys have ideas, and I only merge them.

Maybe it's possible to replace main nim package tree to one of your repositories. I will support moving this repo and change nim package repo to make one of you owner of `nim-glm`. 

I cannot contribute to this repo today.

**Pull request merged**
